[project]
scalaVersion       = "2.13.0"
scalaJsVersion     = "0.6.28"
scalaNativeVersion = "0.3.9"

[module.demo]
root    = "."
targets = ["jvm", "js", "native"]
sources = ["src/"]

[module.demo.native]
scalaVersion = "2.11.12"
